drop table Customer;
create table Customer 
(
  customerId NUMBER GENERATED by default on null as IDENTITY,
  customerName VARCHAR2(100) not null,
  address VARCHAR2(250),
  CONSTRAINT customer_pk PRIMARY KEY(customerId)
  --CONSTRAINT vehicle_fk FOREIGN KEY (vehicleID) REFERENCES Vehicle(vehicleID)
);

drop table Vehicle;
CREATE TABLE Vehicle (
    vehicleID varchar(50) not null,
    registrationNo varchar(50) not null,
    status char(1) DEFAULT 'Y' check (status in ('Y','N')) ,
    lastActiveTime TIMESTAMP default current_timestamp not null,
    lastModified TIMESTAMP default current_timestamp not null,
    customerId NUMBER not null,
    CONSTRAINT vehicle_pk PRIMARY KEY(vehicleID),
    CONSTRAINT customer_fk FOREIGN KEY (customerId) REFERENCES Customer(customerId)
);

insert into Customer (customerName,address) values('Kalles Grustransporter AB','Cementvägen 8, 111 11 Södertälje');
insert into Customer (customerName,address) values('Johans Bulk AB','Balkvägen 12, 222 22 Stockholm');
insert into Customer (customerName,address) values('Haralds Värdetransporter AB','Budgetvägen 1, 333 33 Uppsala');

insert into Vehicle (vehicleID, registrationNo, customerId) values('YS2R4X20005399401','ABC123', (select customerId from Customer where customerName like 'Kalles Grustransporter AB'));
insert into Vehicle (vehicleID, registrationNo, customerId) values('VLUR4X20009093588','DEF456', (select customerId from Customer where customerName like 'Kalles Grustransporter AB'));
insert into Vehicle (vehicleID, registrationNo, customerId) values('VLUR4X20009048061','GHI789', (select customerId from Customer where customerName like 'Kalles Grustransporter AB'));
insert into Vehicle (vehicleID, registrationNo, customerId) values('YS2R4X20005388011','JKL012', (select customerId from Customer where customerName like 'Johans Bulk AB'));
insert into Vehicle (vehicleID, registrationNo, customerId) values('YS2R4X20005387949','MNO345', (select customerId from Customer where customerName like 'Johans Bulk AB'));
insert into Vehicle (vehicleID, registrationNo, customerId) values('VLUR4X20009048066','PQR678', (select customerId from Customer where customerName like 'Haralds Värdetransporter AB'));
insert into Vehicle (vehicleID, registrationNo, customerId) values('YS2R4X20005387055','STU901', (select customerId from Customer where customerName like 'Haralds Värdetransporter AB'));

select * from  CUSTOMER;
select * from  VEHICLE;
